cluster-start:
	minikube start --vm-driver=hyperkit --container-runtime=docker --memory 8192

cluster-status:
	minikube status

cluster-stop:
	minikube stop

cluster-delete:
	minikube delete

cluster-dashboard:
	minikube dashboard

cluster-info:
	kubectl cluster-info

cluster-nodes:
	kubectl get nodes

cluster-version:
	kubectl version

